version: '3'

services:
  erp_db:
    image: mysql
    container_name: erp_db
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ice
      MYSQL_PASSWORD: ice
    ports:
      - "6033:3306"
    volumes:
      - ./init.sql:/data/application/init.sql
      - dbdata:/var/lib/mysql
    networks:
      vpcbr:
        ipv4_address: 10.2.0.36
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: erp_db
    networks:
      vpcbr:
        ipv4_address: 10.2.0.88
  # add an apache server with the php application in the current folder
  apache:
    image: php:7.2-apache
    restart: always
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
    networks:
      vpcbr:
        ipv4_address: 10.2.0.80

volumes:
  dbdata: